services:
    OHMedia\AccordionBundle\Controller\AccordionController:
        tags: ["container.service_subscriber", "controller.service_arguments"]
        autowire: true

    OHMedia\AccordionBundle\Controller\AccordionItemController:
        tags: ["container.service_subscriber", "controller.service_arguments"]
        autowire: true

    OHMedia\AccordionBundle\Controller\FaqController:
        tags: ["container.service_subscriber", "controller.service_arguments"]
        autowire: true

    OHMedia\AccordionBundle\Controller\FaqQuestionController:
        tags: ["container.service_subscriber", "controller.service_arguments"]
        autowire: true

    OHMedia\AccordionBundle\Service\AccordionEntityChoice:
        tags: ["oh_media_security.entity_choice"]
        autowire: true

    OHMedia\AccordionBundle\Service\FaqEntityChoice:
        tags: ["oh_media_security.entity_choice"]
        autowire: true

    OHMedia\AccordionBundle\Service\AccordionNavItemProvider:
        tags: ["oh_media_backend.nav_item_provider"]
        autowire: true

    OHMedia\AccordionBundle\Service\FaqNavItemProvider:
        tags: ["oh_media_backend.nav_item_provider"]
        autowire: true

    OHMedia\AccordionBundle\Repository\AccordionRepository:
        autowire: true
        tags: ["doctrine.repository_service"]

    OHMedia\AccordionBundle\Repository\AccordionItemRepository:
        autowire: true
        tags: ["doctrine.repository_service", "oh_media_wysiwyg.repository"]

    OHMedia\AccordionBundle\Repository\FaqRepository:
        autowire: true
        tags: ["doctrine.repository_service"]

    OHMedia\AccordionBundle\Repository\FaqQuestionRepository:
        autowire: true
        tags: ["doctrine.repository_service", "oh_media_wysiwyg.repository"]

    OHMedia\AccordionBundle\Security\Voter\AccordionVoter:
        autowire: true
        tags: ["security.voter"]

    OHMedia\AccordionBundle\Security\Voter\AccordionItemVoter:
        autowire: true
        tags: ["security.voter"]

    OHMedia\AccordionBundle\Security\Voter\FaqVoter:
        autowire: true
        tags: ["security.voter"]

    OHMedia\AccordionBundle\Security\Voter\FaqQuestionVoter:
        autowire: true
        tags: ["security.voter"]

    OHMedia\AccordionBundle\Twig\WysiwygExtension:
        autowire: true
        tags: ["twig.extension", "oh_media_wysiwyg.extension"]
