services:
    _defaults:
        autowire: true
        autoconfigure: true

    OHMedia\AccordionBundle\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/OHMediaAccordionBundle.php'
